import type { Update, UpdateKind } from "../types/update.types";

export type UpdateBlueprint = Pick<
  Update,
  "name" | "kind" | "channel" | "fromVersion" | "toVersion" | "affectedTags"
> & {
  /** Anchor offset from base (negative = past, positive = future). */
  startMinutesAgo: number;
  targetPct: number;
  successPct: number;
  failurePct: number;
};

export const UPDATE_BLUEPRINTS: UpdateBlueprint[] = [
  {
    name: "macOS 14.2 security patch",
    kind: "os",
    channel: "stable",
    fromVersion: "14.1",
    toVersion: "14.2",
    affectedTags: [],
    startMinutesAgo: 60 * 20,
    targetPct: 0.8,
    successPct: 0.94,
    failurePct: 0.06,
  },
  {
    name: "Endpoint agent 8.4.2",
    kind: "security",
    channel: "stable",
    fromVersion: "8.4.1",
    toVersion: "8.4.2",
    affectedTags: [],
    startMinutesAgo: 60 * 14,
    targetPct: 0.9,
    successPct: 0.99,
    failurePct: 0.01,
  },
  {
    name: "VPN client 3.2",
    kind: "app",
    channel: "stable",
    fromVersion: "3.1.4",
    toVersion: "3.2.0",
    affectedTags: ["remote", "field"],
    startMinutesAgo: 60 * 11,
    targetPct: 0.6,
    successPct: 0.92,
    failurePct: 0.03,
  },
  {
    name: "Wave 4 patch rollout",
    kind: "os",
    channel: "stable",
    fromVersion: "14.1",
    toVersion: "14.2",
    affectedTags: ["engineering"],
    startMinutesAgo: 60 * 4,
    targetPct: 0.4,
    successPct: 0.72,
    failurePct: 0.02,
  },
  {
    name: "Chrome enterprise 132",
    kind: "app",
    channel: "stable",
    fromVersion: "131",
    toVersion: "132",
    affectedTags: [],
    startMinutesAgo: 60 * 30,
    targetPct: 0.7,
    successPct: 0.98,
    failurePct: 0.02,
  },
  {
    name: "Certificate rotation",
    kind: "security",
    channel: "stable",
    fromVersion: "2026-Q1",
    toVersion: "2026-Q3",
    affectedTags: [],
    startMinutesAgo: 60 * 48,
    targetPct: 1,
    successPct: 1,
    failurePct: 0,
  },
  {
    name: "Design suite 24.4",
    kind: "app",
    channel: "beta",
    fromVersion: "24.3",
    toVersion: "24.4",
    affectedTags: ["design"],
    startMinutesAgo: 60 * 9,
    targetPct: 0.5,
    successPct: 0.9,
    failurePct: 0.06,
  },
  {
    name: "macOS 14.3 canary",
    kind: "os",
    channel: "canary",
    fromVersion: "14.2",
    toVersion: "14.3",
    affectedTags: ["engineering"],
    startMinutesAgo: 60 * 2,
    targetPct: 0.05,
    successPct: 0.8,
    failurePct: 0.15,
  },
  // future scheduled
  {
    name: "macOS 14.3 stable wave 1",
    kind: "os",
    channel: "stable",
    fromVersion: "14.2",
    toVersion: "14.3",
    affectedTags: [],
    startMinutesAgo: -60 * 2,
    targetPct: 0.3,
    successPct: 0,
    failurePct: 0,
  },
  {
    name: "Financial suite 12.1",
    kind: "app",
    channel: "stable",
    fromVersion: "12.0",
    toVersion: "12.1",
    affectedTags: ["finance"],
    startMinutesAgo: -60 * 6,
    targetPct: 0.9,
    successPct: 0,
    failurePct: 0,
  },
  {
    name: "Compliance audit tools 5.0",
    kind: "app",
    channel: "stable",
    fromVersion: "4.8",
    toVersion: "5.0",
    affectedTags: ["sox", "hipaa"],
    startMinutesAgo: -60 * 10,
    targetPct: 1,
    successPct: 0,
    failurePct: 0,
  },
];

export const UPDATE_KIND_LABELS: Record<UpdateKind, string> = {
  os: "OS Update",
  security: "Security Update",
  app: "App Update",
};
